# Generated by Django 2.2.4 on 2022-02-21 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='books',
        ),
        migrations.AddField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='users',
            field=models.ManyToManyField(related_name='wishes', to='wish_app.User'),
        ),
    ]
