# Generated by Django 2.2.4 on 2022-02-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0003_auto_20220221_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users',
        ),
    ]
