# Generated by Django 2.2.4 on 2022-02-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restfull_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shows',
            new_name='Show',
        ),
    ]
