# Generated by Django 2.2.4 on 2022-02-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restfull_app', '0002_auto_20220214_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Shows',
        ),
    ]
