# Generated by Django 2.2.4 on 2022-02-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restfull_app', '0003_auto_20220214_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
